### ISSUE TITLE
Implementar estructura de plantilla mediante PHP

### ISSUE THREAD

**Issue by Martin-IyM** [sofiasoldano/finlandia#2]
Conviene ya desde el principio ir incluyendo las partes que se repiten del sitio como includes de php, de manera similar a como está armada actualmente la plantilla que genera el html del sitio.

**Comment by Martin-IyM** [comment]
@sofiasoldano fijate lo que arme en el PR #6, la idea es seguir con una estructura que nos permita evitar tener que editar multiples archivos para cambios que se replican en varios lugares, y además ir preparando la maqueta para el sistema real en que se va a utilizar.

**Comment by sofiasoldano** [comment]
Esto también, ahí lo cambié.
